### ISSUE TITLE
Losing my peace of mindfulness :D

### ISSUE THREAD

**Issue by anna-pokhilenko** [anna-pokhilenko/modularity-mindfulness#1]
Hello, Thomas! I am not sure if you are answering the issues during the break, but I decided to work through the Web Dev 3 during the summer so I wouldn't forget the code and got a bit stuck on that website. 

My major problem is those cards, I have a bit of a problem with content-distribute. 
And I sometimes use max-width in MQs but Markbot yells at me about that. 

@thomasjbradley

**Comment by thomasjbradley** [comment]
Wonderful idea! It will really help out when you start again in September.

There’s no solution to using `max-width` in media queries—you shouldn’t use it. Using `max-width` means you’re thinking big screens down to small screens—but we always do mobile first thinking.

---

The distribution in this exercise is really difficult because it needs to go in so many places.

- https://github.com/anna-pokhilenko/modularity-mindfulness/blob/gh-pages/index.html#L64
`.unit-content-distribute` & `.content-fill`

- https://github.com/anna-pokhilenko/modularity-mindfulness/blob/gh-pages/index.html#L70
`.unit-content-distribute` & `.content-fill`

- https://github.com/anna-pokhilenko/modularity-mindfulness/blob/gh-pages/index.html#L73
`.content-fill`
